/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.lcsim.recon.tracking.seedtracker.strategybuilder;

import org.lcsim.event.EventHeader;
import org.lcsim.event.MCParticle;

/**
 * A particle filter is applied to MCParticles in the training step. LayerSets 
 * are not generated by MCParticles which do not pass the filters. Note that 
 * a minimum number of layers hit is necessary in addition to passing the filter. 
 * 
 * The default behavior for StrategyBuilder is to use a StrategyBasedFilter, which
 * gets cutoffs for DCA, z0 and pt based on prototype strategy. 
 * 
 * 
 * @author cozzy
 */
public interface IParticleFilter {
    
    /**
     * Returns true if the MCParticle passes the filter, false otherwise. Called
     * for every MCParticle by StrategyBuilder. 
     * 
     * @param p The test MCParticle
     * @return
     */
    public boolean passes(MCParticle p); 
    
    /**
     * This method is called for each event by StrategyBuilder.  
     * @param event
     */
    public void setEvent(EventHeader event);  
}
