package org.lcsim.plugin.browser;

import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import org.lcsim.event.EventHeader;
import org.lcsim.event.EventHeader.LCMetaData;
import org.lcsim.plugin.browser.sort.DefaultSortableTableModel;
import org.lcsim.plugin.browser.sort.TableSorter;
/**
 *
 * @author tonyj
 */
class EventHeaderPanel extends JPanel
{
   private DefaultTableModel blockModel;
   /** Creates new form EventHeaderPanel */
   EventHeaderPanel()
   {
      initComponents();
      blockModel = (DefaultTableModel) blockTable.getModel();
      blockTable.setModel(new DefaultSortableTableModel(blockModel));
      
      new TableSorter(blockTable).setSortOnColumn(0);
   }
   void setData(EventHeader event)
   {
      DefaultTableModel model = (DefaultTableModel) headerTable.getModel();
      if (event != null)
      {
         model.setValueAt(String.valueOf(event.getRunNumber()),0,1);
         model.setValueAt(String.valueOf(event.getEventNumber()),1,1);
         long ts = event.getTimeStamp();
         if (ts > 1e15) model.setValueAt(new Date(ts/1000000),2,1);
         else           model.setValueAt(String.valueOf(ts),2,1);
         model.setValueAt(event.getDetectorName(),3,1);
         
         // Add additional event parameters for Norman.  --JM
         Map<String,String[]> sparams = event.getStringParameters();
         Map<String,int[]> iparams = event.getIntegerParameters();
         Map<String,float[]> fparams = event.getFloatParameters();
         
         float weight = 1.0f;
         if (fparams.containsKey("_weight"))
        	 weight = fparams.get("_weight")[0];
         
         int idrup = 0;
         if (iparams.containsKey("_idrup"))
        	 idrup = iparams.get("_idrup")[0];
         
         String slicVersion = "";
         if (sparams.containsKey("SLIC_VERSION"))
        	 slicVersion = sparams.get("SLIC_VERSION")[0];
         
         String geantVersion = "";
         if (sparams.containsKey("GEANT4_VERSION"))
        	 geantVersion = sparams.get("GEANT4_VERSION")[0];

         model.setValueAt(weight, 4, 1);
         model.setValueAt(idrup, 5, 1);
         model.setValueAt(slicVersion, 6, 1);
         model.setValueAt(geantVersion, 7, 1);
      }
      else for (int i=0; i<8; i++) model.setValueAt("",i,1);
      
      blockModel.setRowCount(0);
      if (event != null)
      {
         List<List<Object>> collections = event.get(Object.class);
         for (List<Object> list : collections)
         {
            LCMetaData meta = event.getMetaData(list);            
            blockModel.addRow(new Object[]{meta.getName(),meta.getType().getName(), list.size()});          
         }
      }
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        javax.swing.JScrollPane blockScroll;
        javax.swing.JPanel jPanel1;
        javax.swing.JPanel jPanel2;

        jPanel1 = new javax.swing.JPanel();
        headerTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        blockScroll = new javax.swing.JScrollPane();
        blockTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder("LCIO Event Header"));
        headerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Run", null},
                {"Event", null},
                {"Time Stamp", null},
                {"Detector Name", null},
                {"Event Weight", null},
                {"IDRUP", null},
                {"SLIC Version", null},
                {"Geant4 Version", null}
            },
            new String []
            {
                "Title 1", "Title 2"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jPanel1.add(headerTable, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Collections"));
        blockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Name", "Type", "Size"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        blockScroll.setViewportView(blockTable);

        jPanel2.add(blockScroll, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable blockTable;
    private javax.swing.JTable headerTable;
    // End of variables declaration//GEN-END:variables
   
}
