/*
 * PrefsDialog.java
 *
 * Created on December 9, 2002, 6:40 PM
 */

package org.freehep.jas.extension.spreadsheet;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  tonyj
 */
class PrefsDialog extends javax.swing.JPanel
{
   
   /** Creates new form PrefsDialog */
   public PrefsDialog(SpreadsheetPlugin plugin)
   {
      rows = new SpinnerNumberModel(plugin.getDefaultRows(),1,1000,1);
      columns = new SpinnerNumberModel(plugin.getDefaultColumns(),1,1000,1);
      width = new SpinnerNumberModel(plugin.getColumnWidth(),10,400,1);
      initComponents();
   }
   void apply(SpreadsheetPlugin plugin)
   {
      plugin.setDefaultRows(rows.getNumber().intValue());
      plugin.setDefaultColumns(columns.getNumber().intValue());
      plugin.setColumnWidth(width.getNumber().intValue());
   }
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   private void initComponents()//GEN-BEGIN:initComponents
   {
      java.awt.GridBagConstraints gridBagConstraints;

      jLabel1 = new javax.swing.JLabel();
      jSpinner1 = new javax.swing.JSpinner();
      jLabel3 = new javax.swing.JLabel();
      jSpinner2 = new javax.swing.JSpinner();
      jLabel4 = new javax.swing.JLabel();
      jSpinner3 = new javax.swing.JSpinner();

      setLayout(new java.awt.GridBagLayout());

      setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
      setMinimumSize(null);
      setPreferredSize(null);
      jLabel1.setText("Default Rows");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
      add(jLabel1, gridBagConstraints);

      jSpinner1.setModel(rows);
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.weightx = 0.5;
      add(jSpinner1, gridBagConstraints);

      jLabel3.setText("Default Columns");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
      add(jLabel3, gridBagConstraints);

      jSpinner2.setModel(columns);
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.weightx = 0.5;
      add(jSpinner2, gridBagConstraints);

      jLabel4.setText("Column Width");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
      add(jLabel4, gridBagConstraints);

      jSpinner3.setModel(width);
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.weightx = 0.5;
      add(jSpinner3, gridBagConstraints);

   }//GEN-END:initComponents
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JSpinner jSpinner3;
   private javax.swing.JSpinner jSpinner1;
   private javax.swing.JSpinner jSpinner2;
   // End of variables declaration//GEN-END:variables
 
   private SpinnerNumberModel rows;
   private SpinnerNumberModel columns;
   private SpinnerNumberModel width;
}
