package org.freehep.jas.extension.editor;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;

/**
 *
 * @author  turri
 */
public class FontPropertyDialog extends JPanel {
    
    private String currentText;
    private String currentFontSize;
    private String currentFontType;
    private String currentFontStyle;
    private Color  currentColor;
    private SimpleEditor plugin;
    
    /** Creates new form FontPropertyDialog */
    public FontPropertyDialog(SimpleEditor plugin, String[] textFields) {        
        this.plugin = plugin;
        initComponents();
        textComboBox.setModel( new DefaultComboBoxModel( textFields ) );
        setCurrentFields();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   private void initComponents()//GEN-BEGIN:initComponents
   {
      java.awt.GridBagConstraints gridBagConstraints;

      textFieldsPanel = new javax.swing.JPanel();
      textLabel = new javax.swing.JLabel();
      jPanel6 = new javax.swing.JPanel();
      jPanel1 = new javax.swing.JPanel();
      fontPanel = new javax.swing.JPanel();
      fontLabel = new javax.swing.JLabel();
      sizePanel1 = new javax.swing.JPanel();
      sizeLabel = new javax.swing.JLabel();
      stylePanel = new javax.swing.JPanel();
      styleLabel = new javax.swing.JLabel();
      colorPanel = new javax.swing.JPanel();
      colorLabel = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      fontsComboBox = new javax.swing.JComboBox();
      jPanel3 = new javax.swing.JPanel();
      sizeComboBox = new javax.swing.JComboBox();
      jPanel4 = new javax.swing.JPanel();
      styleComboBox = new javax.swing.JComboBox();
      jPanel5 = new javax.swing.JPanel();
      chooseColorButton = new javax.swing.JButton();
      colorSample = new javax.swing.JLabel();
      textComboBox = new javax.swing.JComboBox();

      setLayout(new java.awt.GridBagLayout());

      textFieldsPanel.setLayout(new java.awt.GridBagLayout());

      textFieldsPanel.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
      textLabel.setText("Select Text");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
      gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 6);
      textFieldsPanel.add(textLabel, gridBagConstraints);

      jPanel6.setLayout(new java.awt.GridBagLayout());

      jPanel1.setLayout(new java.awt.GridBagLayout());

      jPanel1.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseEntered(java.awt.event.MouseEvent evt)
         {
            jPanel1MouseEntered(evt);
         }
      });

      fontPanel.setLayout(new java.awt.GridBagLayout());

      fontPanel.setMinimumSize(new java.awt.Dimension(31, 41));
      fontPanel.setPreferredSize(new java.awt.Dimension(35, 25));
      fontLabel.setText("Font");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
      fontPanel.add(fontLabel, gridBagConstraints);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      jPanel1.add(fontPanel, gridBagConstraints);

      sizePanel1.setLayout(new java.awt.GridBagLayout());

      sizePanel1.setPreferredSize(new java.awt.Dimension(35, 25));
      sizeLabel.setText("Size");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
      sizePanel1.add(sizeLabel, gridBagConstraints);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      jPanel1.add(sizePanel1, gridBagConstraints);

      stylePanel.setLayout(new java.awt.GridBagLayout());

      stylePanel.setMinimumSize(new java.awt.Dimension(135, 41));
      stylePanel.setPreferredSize(new java.awt.Dimension(35, 25));
      styleLabel.setText("Style");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
      stylePanel.add(styleLabel, gridBagConstraints);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      jPanel1.add(stylePanel, gridBagConstraints);

      colorPanel.setLayout(new java.awt.GridBagLayout());

      colorPanel.setPreferredSize(new java.awt.Dimension(35, 25));
      colorLabel.setText("Color");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
      colorPanel.add(colorLabel, gridBagConstraints);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      jPanel1.add(colorPanel, gridBagConstraints);

      jPanel2.setLayout(new java.awt.GridBagLayout());

      getAvailableFonts();
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
      jPanel2.add(fontsComboBox, gridBagConstraints);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      jPanel1.add(jPanel2, gridBagConstraints);

      jPanel3.setLayout(new java.awt.GridBagLayout());

      sizeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "10", "12", "14", "16", "18", "20" }));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
      jPanel3.add(sizeComboBox, gridBagConstraints);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      jPanel1.add(jPanel3, gridBagConstraints);

      jPanel4.setLayout(new java.awt.GridBagLayout());

      styleComboBox.setMaximumRowCount(4);
      styleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plain", "Bold", "Italic", "Bold & Italic" }));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
      jPanel4.add(styleComboBox, gridBagConstraints);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      jPanel1.add(jPanel4, gridBagConstraints);

      jPanel5.setLayout(new java.awt.GridBagLayout());

      jPanel5.setBorder(new javax.swing.border.EtchedBorder());
      chooseColorButton.setText("...");
      chooseColorButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            chooseColorButtonActionPerformed(evt);
         }
      });
      chooseColorButton.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mousePressed(java.awt.event.MouseEvent evt)
         {
            chooseColorButtonMousePressed(evt);
         }
      });

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 0;
      jPanel5.add(chooseColorButton, gridBagConstraints);

      colorSample.setText("ccc");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      jPanel5.add(colorSample, gridBagConstraints);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      jPanel1.add(jPanel5, gridBagConstraints);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      jPanel6.add(jPanel1, gridBagConstraints);

      textComboBox.setMaximumRowCount(3);
      textComboBox.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            textComboBoxActionPerformed(evt);
         }
      });

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      jPanel6.add(textComboBox, gridBagConstraints);

      textFieldsPanel.add(jPanel6, new java.awt.GridBagConstraints());

      add(textFieldsPanel, new java.awt.GridBagConstraints());

   }//GEN-END:initComponents

    private void chooseColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseColorButtonActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_chooseColorButtonActionPerformed
    
    private void chooseColorButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseColorButtonMousePressed
        ColorChooser cc = new ColorChooser(this);
        cc.setLocationRelativeTo(this);
        cc.setVisible(true);
    }//GEN-LAST:event_chooseColorButtonMousePressed
    
    private void textComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textComboBoxActionPerformed
        setCurrentFields();
    }//GEN-LAST:event_textComboBoxActionPerformed
    
    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        textComboBox.hidePopup();
        fontsComboBox.hidePopup();
        sizeComboBox.hidePopup();
        styleComboBox.hidePopup();
    }//GEN-LAST:event_jPanel1MouseEntered
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
    }//GEN-LAST:event_closeDialog
    
    
    private void getAvailableFonts() {
        GraphicsEnvironment gEnv = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String envfonts[] = gEnv.getAvailableFontFamilyNames();
        fontsComboBox.setModel( new DefaultComboBoxModel(envfonts) );
    }
    
    public void apply() {
        plugin.setFontSize(currentText, (String)sizeComboBox.getSelectedItem());
        plugin.setFontType(currentText, (String)fontsComboBox.getSelectedItem());
        plugin.setFontStyle(currentText, (String)styleComboBox.getSelectedItem());
        plugin.setColor(currentText, currentColor);
    }
    
    private void setCurrentFields() {
        currentText = (String)textComboBox.getSelectedItem();
        currentFontSize = plugin.getFontSize(currentText);
        currentFontType = plugin.getFontType(currentText);
        currentFontStyle = plugin.getFontStyle(currentText);
        setColor( plugin.getFontColor(currentText) );
        fontsComboBox.setSelectedItem( currentFontType );
        sizeComboBox.setSelectedItem( currentFontSize );
        styleComboBox.setSelectedItem( currentFontStyle );
    }    
    
    private void setColor( Color color ) {
        jPanel5.setForeground(color);
        jPanel5.setBackground(color);
        colorSample.setForeground(color);
        colorSample.setBackground(color);
        currentColor = color;
    }
    
    
    
    
    private class ColorChooser extends JDialog {

        private JPanel  buttonPanel = new JPanel();
        private JButton okButton = new JButton("OK");
        private JButton applyButton = new JButton("Apply");
        private JButton cancelButton = new JButton("Cancel");
        private FontPropertyDialog dialog;
        private JColorChooser cc;
  
        ColorChooser(FontPropertyDialog dialog) {
            super( (Dialog)SwingUtilities.getAncestorOfClass(Dialog.class, dialog), true );
            setTitle("Color Chooser");
            this.dialog = dialog;
            
            GridBagConstraints gridBagConstraints = new GridBagConstraints();

            cc = new JColorChooser();
            getContentPane().setLayout(new GridBagLayout());
            cc.setVisible(true);
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 0;
            getContentPane().add(cc,gridBagConstraints);

            okButton.addMouseListener(new MouseAdapter() {
                public void mousePressed(MouseEvent evt) {
                    setColor();
                    close();
                }
            });
            
            applyButton.addMouseListener(new MouseAdapter() {
                public void mousePressed(MouseEvent evt) {
                    setColor();
                }
            });

            cancelButton.addMouseListener(new MouseAdapter() {
                public void mousePressed(MouseEvent evt) {
                    close();
                }
            });
            
            buttonPanel.setLayout(new GridBagLayout());
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 0;
            buttonPanel.add(okButton, gridBagConstraints);
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = 0;
            buttonPanel.add(applyButton, gridBagConstraints);
            gridBagConstraints.gridx = 2;
            gridBagConstraints.gridy = 0;
            buttonPanel.add(cancelButton, gridBagConstraints);
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 1;
            getContentPane().add(buttonPanel,gridBagConstraints);
            pack();
        }
        
        public void close() {
            setVisible(false);
            dispose();
        }
        
        public void setColor() {
            dialog.setColor(cc.getColor());
        }
        
        
    }
    
    
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton chooseColorButton;
   private javax.swing.JLabel colorLabel;
   private javax.swing.JPanel colorPanel;
   private javax.swing.JLabel colorSample;
   private javax.swing.JLabel fontLabel;
   private javax.swing.JPanel fontPanel;
   private javax.swing.JComboBox fontsComboBox;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JPanel jPanel6;
   private javax.swing.JComboBox sizeComboBox;
   private javax.swing.JLabel sizeLabel;
   private javax.swing.JPanel sizePanel1;
   private javax.swing.JComboBox styleComboBox;
   private javax.swing.JLabel styleLabel;
   private javax.swing.JPanel stylePanel;
   private javax.swing.JComboBox textComboBox;
   private javax.swing.JPanel textFieldsPanel;
   private javax.swing.JLabel textLabel;
   // End of variables declaration//GEN-END:variables
    
}
