package org.freehep.jas.extension.tupleExplorer.cut;

import java.util.Vector;
import org.freehep.jas.extension.tupleExplorer.cut.NTupleListCellRenderer;

/**
 *
 * @author  tonyj
 */
public class AddCutToCutSetDialog extends javax.swing.JDialog {

   /** Creates new form AddCutToCutSetDialog */
    public AddCutToCutSetDialog(java.awt.Dialog parent, Vector cuts) {
        super(parent, true);
        this.cuts = cuts;
        initComponents();
        getRootPane().setDefaultButton(okButton);
    }

    public AddCutToCutSetDialog(java.awt.Frame parent, Vector cuts) {
        super(parent, true);
        this.cuts = cuts;
        initComponents();
        getRootPane().setDefaultButton(okButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        cutList = new javax.swing.JList(cuts);
        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Cut");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cutList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cutList.setCellRenderer(new NTupleListCellRenderer());
        cutList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                cutListValueChanged(evt);
            }
        });
        cutList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cutListMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(cutList);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        okButton.setMnemonic('O');
        okButton.setText("OK");
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel1.add(okButton);

        cancelButton.setMnemonic('C');
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.add(cancelButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void cutListMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cutListMouseClicked
    {//GEN-HEADEREND:event_cutListMouseClicked
       if (evt.getClickCount() == 2 && okButton.isEnabled()) okButton.doClick();
    }//GEN-LAST:event_cutListMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
       dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {//GEN-HEADEREND:event_okButtonActionPerformed
       selectedCut = (Cut) cutList.getSelectedValue();
       dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cutListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_cutListValueChanged
    {//GEN-HEADEREND:event_cutListValueChanged
       okButton.setEnabled(cutList.getSelectedValue() != null);
    }//GEN-LAST:event_cutListValueChanged

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    Cut getSelectedCut()
    {
       return selectedCut;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JList cutList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private Cut selectedCut;
    private Vector cuts;
}
