package org.freehep.jas.extension.aida;

/**
 *
 * @author tonyj
 * @version $Id: AidaPreferencePanel.java 13893 2011-09-28 23:42:34Z tonyj $
 */
class AidaPreferencePanel extends javax.swing.JPanel
{
   private AIDAPlugin plugin;
   /** Creates new form AidaPreferencePanel */
   AidaPreferencePanel(AIDAPlugin plugin)
   {
      this.plugin = plugin;
      initComponents();
      boolean showTitle = plugin.isShowNamesAndTitles();
      nameTitleGroup.setSelected(showTitle ? nameAndTitle.getModel() : nameOnly.getModel(), true);
   }
   boolean apply()
   {
      plugin.setShowNamesAndTitles(nameTitleGroup.getSelection() == nameAndTitle.getModel());
      return true;
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        nameTitleGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nameAndTitle = new javax.swing.JRadioButton();
        nameOnly = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder("AIDA Tree"));
        nameAndTitle.setMnemonic('T');
        nameAndTitle.setText("Show name and title (if different)");
        nameTitleGroup.add(nameAndTitle);
        jPanel1.add(nameAndTitle, java.awt.BorderLayout.SOUTH);

        nameOnly.setMnemonic('N');
        nameOnly.setText("Show only name");
        nameTitleGroup.add(nameOnly);
        jPanel1.add(nameOnly, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jPanel1, gridBagConstraints);

    }//GEN-END:initComponents
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nameAndTitle;
    private javax.swing.JRadioButton nameOnly;
    private javax.swing.ButtonGroup nameTitleGroup;
    // End of variables declaration//GEN-END:variables
   
}
