package org.freehep.jas.extensions.root;

/**
 *
 * @author tonyj
 * @versio $Id: AIDARootPreferences.java 13893 2011-09-28 23:42:34Z tonyj $
 */
class AIDARootPreferences extends javax.swing.JPanel
{
   private AIDARootPlugin plugin;
   /** Creates new form AIDARootPreferences */
   AIDARootPreferences(AIDARootPlugin plugin)
   {
      this.plugin = plugin;
      initComponents();
      cycleGroup.setSelected(plugin.isShowAllCycles() ? showAll.getModel() : showLatest.getModel(), true);
   }
   boolean apply()
   {
      plugin.setShowAllCycles(showAll.isSelected());
      return true;
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   private void initComponents()//GEN-BEGIN:initComponents
   {
      javax.swing.JPanel jPanel1;

      cycleGroup = new javax.swing.ButtonGroup();
      jPanel1 = new javax.swing.JPanel();
      showAll = new javax.swing.JRadioButton();
      showLatest = new javax.swing.JRadioButton();

      setLayout(new java.awt.GridBagLayout());

      jPanel1.setLayout(new java.awt.BorderLayout());

      jPanel1.setBorder(new javax.swing.border.TitledBorder("Versioning"));
      showAll.setMnemonic('A');
      showAll.setText("Show all cycles");
      cycleGroup.add(showAll);
      jPanel1.add(showAll, java.awt.BorderLayout.SOUTH);

      showLatest.setMnemonic('L');
      showLatest.setText("Show only latest cycle");
      cycleGroup.add(showLatest);
      jPanel1.add(showLatest, java.awt.BorderLayout.NORTH);

      add(jPanel1, new java.awt.GridBagConstraints());

   }//GEN-END:initComponents
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.ButtonGroup cycleGroup;
   private javax.swing.JRadioButton showAll;
   private javax.swing.JRadioButton showLatest;
   // End of variables declaration//GEN-END:variables
   
}
