package org.freehep.jas.util.waitcursor;

import junit.framework.*;

/**
 *
 * @author Tony Johnson
 */
public class WaitCursorSuite extends TestCase
{
   
   public WaitCursorSuite(java.lang.String testName)
   {
      super(testName);
   }
   
   /**
    * suite method automatically generated by JUnit module
    */
   public static Test suite()
   {
      TestSuite suite = new TestSuite("WaitcursorSuite");
      suite.addTest(new TestSuite(WaitCursorEventQueueTest.class));
      suite.addTest(new TestSuite(DelayTimerTest.class));
      return suite;
   }
   
   public static void main(java.lang.String[] args)
   {
      junit.textui.TestRunner.run(suite());
   }
}
