package org.lcsim.plugin.conditions;

import javax.swing.DefaultComboBoxModel;
import org.freehep.application.Application;
import org.freehep.swing.wizard.Finishable;
import org.freehep.swing.wizard.WizardPage;
import org.lcsim.conditions.*;

/**
 *
 * @author tonyj
 * @version $Id: ConditionsAliasWizardPage.java,v 1.2 2007/04/09 05:11:11 tonyj Exp $
 */
class ConditionsAliasWizardPage extends WizardPage implements Finishable
{
   private ConditionsWizardPage wp;
   /** Creates new form ConditionsAliasWizardPage */
   ConditionsAliasWizardPage(ConditionsWizardPage wp)
   {
      this.wp = wp;
      initComponents();
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      java.awt.GridBagConstraints gridBagConstraints;

      jLabel1 = new javax.swing.JLabel();
      jComboBox1 = new javax.swing.JComboBox();

      setLayout(new java.awt.GridBagLayout());

      jLabel1.setText("Set as alias for");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
      add(jLabel1, gridBagConstraints);

      jComboBox1.setModel(new DefaultComboBoxModel(ConditionsReader.getDetectorNames().toArray()));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
      add(jComboBox1, gridBagConstraints);

   }// </editor-fold>//GEN-END:initComponents

   public void onFinish()
   {
      try
      {
         wp.addAlias(jComboBox1.getSelectedItem().toString());
         dispose();
      }
      catch (ConditionsManager.ConditionsNotFoundException x)
      {
         Application.error(this,"Error creating alias",x);
      }
   }
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox jComboBox1;
   private javax.swing.JLabel jLabel1;
   // End of variables declaration//GEN-END:variables
   
}
