package org.freehep.jas.extensions.text.core;

import junit.framework.*;

/**
 *
 * @author Tony Johnson
 */
public class CoreSuite extends TestCase
{
   
   public CoreSuite(java.lang.String testName)
   {
      super(testName);
   }
   
   /**
    * suite method automatically generated by JUnit module
    */
   public static Test suite()
   {
      TestSuite suite = new TestSuite("AidaSuite");
      suite.addTest(org.freehep.jas.extensions.text.core.ColumnTokenizerTest.suite());
      suite.addTest(org.freehep.jas.extensions.text.core.PatternTokenizerTest.suite());
      suite.addTest(org.freehep.jas.extensions.text.core.BufferedLineSourceTest.suite());
      suite.addTest(org.freehep.jas.extensions.text.core.InMemoryLineSourceTest.suite());
      suite.addTest(org.freehep.jas.extensions.text.core.TokenSourceTest.suite());
      suite.addTest(org.freehep.jas.extensions.text.core.IntegerFormatTest.suite());
      suite.addTest(org.freehep.jas.extensions.text.core.DoubleFormatTest.suite());
      suite.addTest(org.freehep.jas.extensions.text.core.TypeScannerTest.suite());
      return suite;
   }
}
