package org.freehep.jas.extensions.recordloop;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author tonyj
 * @version $Id: GoOptions.java 13880 2011-09-20 05:55:36Z tonyj $
 */
class GoOptions extends javax.swing.JPanel {
    
    /** Creates new form JPanel */
    GoOptions(boolean stop, int max) {
        initComponents();
        maxRecords.setValue(new Integer(max));
        stopCheckbox.setSelected(stop);      
    }
    int getMaxRecords()
    {
        return ((Number) maxRecords.getValue()).intValue();
    }
    boolean isStopAfter()
    {
        return stopCheckbox.isSelected();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        javax.swing.JLabel jLabel1;

        stopCheckbox = new javax.swing.JCheckBox();
        maxRecords = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        stopCheckbox.setMnemonic('S');
        stopCheckbox.setText("Stop afer");
        stopCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                stopCheckboxStateChanged(evt);
            }
        });

        add(stopCheckbox);

        maxRecords.setModel(new SpinnerNumberModel(100,1,1000000,1));
        add(maxRecords);

        jLabel1.setText("records");
        add(jLabel1);

    }//GEN-END:initComponents

    private void stopCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_stopCheckboxStateChanged
        maxRecords.setEnabled(stopCheckbox.isSelected());
    }//GEN-LAST:event_stopCheckboxStateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner maxRecords;
    private javax.swing.JCheckBox stopCheckbox;
    // End of variables declaration//GEN-END:variables
    
}
